### ISSUE TITLE
Mixed tabs and spaces in generated code

### ISSUE THREAD

**Issue by zxqfox** [bem/generator-bem-stub#100]
https://github.com/bem/generator-bem-stub/blob/master/app/templates/.enb/make.js#L13 & etc.

**Comment by eGavr** [comment]
Any suggestions about the refactoring are welcome!

**Comment by zxqfox** [comment]
Suggest `.replace('\t', '    ')` at the output ;-)

**Comment by eGavr** [comment]
Pull request? )

**Comment by zxqfox** [comment]
@eGavr What you think?

**Comment by tadatuta** [comment]
@zxqfox looks great, thanks!
