### ISSUE TITLE
`enb` build doesn't need `bower-npm-install` package

### ISSUE THREAD

**Issue by zxqfox** [bem/generator-bem-stub#107]
I've found that project built with `enb` uses `bower-npm-install` at postinstall instead of `bower i --non-interactive`.

Should we fix that?

**Comment by tadatuta** [comment]
yes, we should

**Comment by eGavr** [comment]
Okey! Will be done.

@zxqfox if you are able to make a pull request, welcome ... ^^

**Comment by zxqfox** [comment]
;-) Yep, sure. But not at this week.

**Comment by eGavr** [comment]
:+1:  Thanks!

I'm looking forward for your PR )

**Comment by eGavr** [comment]
> I've found that project built with enb uses bower-npm-install at postinstall instead of bower i --non-interactive.

Should we remove `bower-npm-install` in cases of using `bem-tools` too?

**Comment by tadatuta** [comment]
@eGavr 
> Should we remove bower-npm-install in cases of using bem-tools too?

nope.
