### ISSUE TITLE
Remove Choose a base library question

### ISSUE THREAD

**Issue by tadatuta** [bem/generator-bem-stub#108]

**Comment by eGavr** [comment]
Окей,  выпелю.

Вопрос про additional  libraries не надо часом выпиливать? там тоже один выбор - bem-components.

**Comment by Guria** [comment]
от bem-components при этом есть возможность отказаться и оставить только bem-core. наверное пусть лучше останется выбор.

**Comment by tadatuta** [comment]
@eGavr да

@Guria да, этот выбор остается.
