### ISSUE TITLE
Feedback for "generator-bem-stub"

### ISSUE THREAD

**Issue by GHostlyFOX** [bem/generator-bem-stub#113]
Пытаюсь ставить генератор на CentOS 6.5

Сыпятся ворнинги:
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.

После того как все прошло получаю сообщение:
> yo@1.4.5 postinstall /root/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory

Everything looks all right!
yo@1.4.5 node_modules/yo
.......

generator-bem-stub@0.5.0 node_modules/generator-bem-stub
.......

Пытаюсь запустить генератор:

yo bem-stub
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:56
				throw err;
				      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:354:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:122:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by eGavr** [comment]
попробуй запустить с правами супер-пользователя, через `sudo`:
```bash
sudo yo bem-stub
```

**Comment by tadatuta** [comment]
@GHostlyFOX @eGavr  не нужно ставить ничего под рутом! `bower` не ставит свои зависимости от суперпользователя, поэтому все равно ничего не получится.
Собственно и исходная проблема возникла из-за того, что что-то было поставлено от суперпользователя. Стоит пройти путь с нуля с правами непривелигерованного пользователя и не используя `sudo`.

**Comment by zxqfox** [comment]
NB: Запрещать запуск под рутом тех приложений, которые не нужно запускать под рутом ;-)

**Comment by tadatuta** [comment]
@eGavr Жека, а пусть действительно генератор ругается, если его запустили под рутом?

**Comment by eGavr** [comment]
Погоди, там же мы ставим генератор глобально и его может система потребовать запускать на админских правах, нет?

**Comment by GHostlyFOX** [comment]
А вот тут проблема. При попытке поставить из под простого пользователя получаю:

npm ERR! Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/tmp/npm.25021/package/cli.js" "rm" "npm" "-gf"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! path /usr/local/bin/npm
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/bin/npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/bin/npm'] errno: -13, code: 'EACCES', path: '/usr/local/bin/npm' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

**Comment by GHostlyFOX** [comment]
Сейчас попробую поставить не глобально...

**Comment by GHostlyFOX** [comment]
Поставил и попробовал запустить:

node-v0.12.0]$ yo bem-stub
? ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes
/usr/local/lib/node_modules/generator-bem-stub/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/lodash/index.js:5697
});
^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-bem-stub/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by eGavr** [comment]
Попробуй поставить глобально (по смыслу генераторы ставятся глобально), но запускать уже не как админ.

**Comment by GHostlyFOX** [comment]
Вот это танцы с бубном... node.js ставить под рутом, генератор ставить под рутом, а запускать генератор под простым пользователем.

При этом в документации о таких танцах ни слова нет.

В общем вроде все сработало, первичный проект создан теперь дальше курить маны и учиться с этим всем работать... единственные сообщения при сборке проекта получил такие:

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN package.json prodaji@0.0.0 No description
npm WARN package.json prodaji@0.0.0 No repository field.
npm WARN package.json prodaji@0.0.0 No README data

npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.6.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.6.0"})


А так в целом проект собрался и появилась структура проекта...

**Comment by GHostlyFOX** [comment]
P.S. Допишите документацию чтобы другие не танцевали так с бубном

**Comment by zxqfox** [comment]
Вообще говоря, нода и yo устанавливаются так, как они сами хотят, это не зависит от конкретного генератора, они ВСЕ должны устанавливаться глобально, потому что сам `yo` так хочет.
http://yeoman.io/ — `npm install -g yo`

Ну а запускать из под рута что бы то ни было — это неправильно. Можно почитать почему, гугл в помощь, и посты типа http://forum.ubuntu.ru/index.php?topic=112306.0

**Comment by eGavr** [comment]
По сути @zxqfox прав. так как поставить nodejs и генератор глобально без прав админа у тебя не получится.
А для запуска самого генератора в доке написано `yo bem-stub`.

**Comment by GHostlyFOX** [comment]
ок... но в данном случае как определить с первого раза какая часть команд установки с какими правами должна запускаться!?

Если бы в самом генераторе не сыпались ошибки, а подсказывали, что он хочет пользователя не рута... а то для меня это получились танцы с бубнами т.к. я только знакомлюсь с node.js и с bem

**Comment by Guria** [comment]
Не стоит node вообще системный для разработки использовать. Рекомендую ставить ноду под юзера через [nvm](https://github.com/creationix/nvm)

**Comment by GHostlyFOX** [comment]
ок. а как быть с генератором который хочет ставиться глобально т.к. не глобально под простым пользователем не получилось его поставить...

**Comment by Guria** [comment]
@GHostlyFOX дело в том, что это общая проблема любых генераторов и других пакетов, которые устанавливаются глобально в системный nodejs. Если в документации написать, чтобы использовали команду sudo пострадают те у кого node установлен через тот же npm.

**Comment by zxqfox** [comment]
> ок... но в данном случае как определить с первого раза какая часть команд установки с какими правами должна запускаться!?

Все, что явно не требует sudo, должно ставиться без sudo. Вот и вся логика.
Если же программа требует sudo — надо 7 раз подумать, нужна ли она. `yo` себя зарекоммендовал, поэтому им и пользуются, и 7 раз уже подумали.

@guria :+1:

**Comment by Guria** [comment]
@GHostlyFOX ещё раз говорю. nodejs ставится через nvm. при этом все глобальные пакеты ставятся под юзером, не требуя прав sudo

**Comment by GHostlyFOX** [comment]
ладно, спасибо всем за помощь... будем курить BEM и учиться его интегрировать с нашим текущим проектом

**Comment by tadatuta** [comment]
BTW, @innabelaya обновила документацию к https://github.com/bem/project-stub и туториал по быстрому старту, там теперь явно говорится о том, что не нужно ставить зависимости под рутом.
Так что было бы круто и в генераторе ругаться, если его пытаются запустить от суперпользователя.

**Comment by andrewblond** [comment]
@tadatuta, а давайте всем советовать `nvm`? Тогда проблемы с рутом не должны проявляться.

**Comment by zxqfox** [comment]
У меня `fish`, ваш `nvm` кривой не работает под `fish`.

**Comment by andrewblond** [comment]
> У меня fish, ваш nvm кривой не работает под fish.

@zxqfox, ты переживёшь ;) 

Можно написать более развёрнутый мануал, про то как поставить ноду, без рута. Но вариант с давайте всем предлагать `nvm` это лучше, чем сейчас, и проще чем мануал.

**Comment by Guria** [comment]
@zxqfox https://github.com/Alex7Kom/nvm-fish/blob/master/README.md
А вообще я думаю тебе советы по установке ноды не нужны :)
А те кто только начинают разбираться, пусть лучше через nvm работают. Лучше чем пакетами разными систему захламлять.
