### ISSUE TITLE
Remove `less` from variants of answers

### ISSUE THREAD

**Issue by eGavr** [bem/generator-bem-stub#115]
Вроде как `less` мы не используем,  а с мажорной версии `enb` планируется вовсе выпилить эту технологию (как сказал мэйнтэйнер @andrewblond технология `css-less` не протестирована, никем не используется).

Сейчас в генераторе используется версия `less@1.x.x`, но давно уже вышла мажорная `less@2.x.x` и при ее использовании технология `css-less` ломается.

Выпилим? 

/сс @tadatuta @andrewblond

**Comment by andrewblond** [comment]
+1

**Comment by tadatuta** [comment]
what about https://github.com/bem/bem-forum-content-ru/issues/250#issuecomment-76176828 ?

**Comment by eGavr** [comment]
Ошибка связана с тем, что `css-less` с `less@2.x.x` не работает.

@andrewblond , раз есть пользователь, то выпиливать не стоит, мб?

**Comment by andrewblond** [comment]
@eGavr, я предлагаю всё же выпиливать и поддерживать только то, что мы можем тестировать.

**Comment by eGavr** [comment]
> @eGavr, я предлагаю всё же выпиливать и поддерживать только то, что мы можем тестировать.

@tadatuta ?

Мне не принципиально, я просто предлагаю)

**Comment by Guria** [comment]
@eGavr @pavelpower использует не `css-less`, а самописный `enb-less`. Насколько я понимаю, выпиливание устаревшей технологии из `generator-bem-stub` его не затронет

**Comment by eGavr** [comment]
Окей, тогда выпиливаю вариант выбора препроцессора `less` в генераторе.
