### ISSUE TITLE
Add a question about beautifying HTML

### ISSUE THREAD

**Issue by tadatuta** [bem/generator-bem-stub#124]
Please refer https://github.com/bem/project-stub/pull/100/ for details

**Comment by eGavr** [comment]
It will be implemented after the merging of the feature to `project-stub`.

**Comment by tadatuta** [comment]
@eGavr actually I won't merge it to `project-stub`

**Comment by eGavr** [comment]
So why do we need this feature in `generator-bem-stub` ?)

**Comment by tadatuta** [comment]
here it could be optional: if user wants it — he gets it. in `project-stub` there's no possibility to choose.
