### ISSUE TITLE
Get rid of bem make config

### ISSUE THREAD

**Issue by tadatuta** [bem/generator-bem-stub#133]
https://github.com/bem/bem-tools/releases/tag/v0.10.0
https://github.com/bem/project-stub/releases/tag/v1.1.0

**Comment by eGavr** [comment]
Have I understood it correctly? Get rid of anything about bem-tools in generator?

**Comment by tadatuta** [comment]
not really. we need to get rid of bem-tools `make.js` config in favour of `enb` make.js (so no matter what will user choose, it's alway enb make.js but all the rest of bem-tools files should be generated as is).
take a look at how it's done in project-stub.

**Comment by eGavr** [comment]
Немного не понял смысла. Пользователь выбирает bem-tools, но будет собирать через enb, только ему еще вдобавок прилетит пачка конфиг-файлов для bem-tools ?

**Comment by blond** [comment]
@eGavr, жизнь — боль! :grimacing:

**Comment by tadatuta** [comment]
@eGavr да, ты все правильно понял, именно так все и будет. смысл этой истории в том, что он тогда сможет продолжать использовать `bem create`
