### ISSUE TITLE
Missed desktop.bundles directory during creation of a skeleton

### ISSUE THREAD

**Issue by koptenkov** [bem/generator-bem-stub#96]
May be it is not a bug, but it is a really confusing.
There is no desktop.bundles directory and all their childs such as .bem, levels.js after creating a stub project. I have doublecheck a video where You presenting a bem-generator-stub at bem.info, and there i see mentioned artifacts.

alexey@linux-1oyh:~/git/test> yo bem-stub
? Enter your project name: project-stub
? Enter a name of the project owner: Ivan Ivanov
? Enter an email of the project owner: 
? Choose a toolkit to build the project: bem-tools
? Choose a base library: bem-core
? Specify additional libraries if needed: bem-components
? Do you want to use design of 'bem-components' library? Yes
? Choose target platforms: desktop
? Choose technologies to be used in the project: BEMJSON, node.js
? Choose a template engine: BEMHTML
? Do you want to build static HTML? Yes
   create project-stub/.bem/level.js
   create project-stub/.bem/levels/blocks.js
   create project-stub/.bem/levels/bundles.js
   create project-stub/.bem/make.js
   create project-stub/.bem/techs/bemjson.js.js
   create project-stub/.bowerrc
   create project-stub/.npmignore
   create project-stub/README.md
   create project-stub/common.blocks/.bem/level.js
   create project-stub/desktop.blocks/.bem/level.js
   create project-stub/bower.json
   create project-stub/package.json

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

nodejs -v: v0.10.31
os: linux opensuse 13.2 x86_64

**Comment by vitkarpov** [comment]
I have the same problem on OS X 10.9.5
There's empty blocks' folders and there're no bundles

**Comment by vitkarpov** [comment]
I've noticed that after installation there's no bundles folder inside template folder.

That's what I have:

```
--- .bem
--- .bowerrc
--- .enb
--- .npmignore
--- README.md
--- blocks
--- bower.json
--- package.json
```

Considering this it's obviously the reason of missing `desktop.bundles` after yo finishes his work

**Comment by eGavr** [comment]
Yep!

I've found a bug, because of your comment! Thank you very much, this problem will be fixed ASAP!

**Comment by eGavr** [comment]
Similar problem in #98

**Comment by vitkarpov** [comment]
Thanks! :+1:

**Comment by eGavr** [comment]
Starting from the version `v0.2.2`, it is the last version now, I've fixed the problem.

Try it and write me back.

**Comment by eGavr** [comment]
@vitkarpov , and a few words about empty blocks' folders.  All blocks' folders should be empty after generation if you use `enb`, if you use `bem-tools` there should be a folder `.bem` with file `levels.js` .

**Comment by vitkarpov** [comment]
Yep. seems I've got it.
Tried 0.2.2 — works fine!
